[uprn_mangle]
api_base_url = "http://localhost"
api_port = 8000
api_prefix = "/api/v1"

db_user = "addressbase"
db_password = "mysecurepassword"
db_name = "addressbase"
db_host = "localhost"
db_port = "5432"
db_table = "addressbase"
